---
title: "Dean Rossano  Final Project"
author: "Dean Rossano"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r cars}
# load packages
library(tidyverse)
library(plotly)
library(sf)
# load data
data = read_rds("cstates_uerates_crates_combined.rds")

filtered_data <- filter(data, NAME ==  "Illinois" | NAME == "California" | 
                          NAME == "Idaho" | NAME == "Indiana")

unemployment_plot <-  plot_ly(filtered_data, x = ~Year, y = ~Unemplyrate, 
                              color = ~NAME) %>% 
                              add_lines()

    
unemployment_plot<- unemployment_plot %>% layout(title = 'Unemployment Rate over Time',

         xaxis = list(title = 'Year'),

         yaxis = list (title = 'Unemployment Rate'))


unemployment_plot

crime_plot <-  plot_ly(filtered_data, x = ~Year, y = ~crime_rate, 
                              color = ~NAME) %>% 
                              add_lines()

crime_plot<- crime_plot %>% layout(title = 'Crime Rate over Time',

         xaxis = list(title = 'Year'),

         yaxis = list (title = 'Crime Rate'))


crime_plot

crime_vs_unemployment_plot <- plot_ly(filtered_data, x = ~Unemplyrate, y = ~crime_rate, color = ~NAME) %>% 
  add_markers()

crime_vs_unemployment_plot
```
