---
title: "Dean Rossano  Final Project"
author: "Dean Rossano"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r cars}
# load packages
library(tidyverse)
library(plotly)
library(sf)
library(ggspatial)
library("viridis") 
# load data
data = read_rds("state_crime_unemp.rds")

# filter data to specified states
filtered_data <- filter(data, NAME ==  "Illinois" | NAME == "California" | 
                          NAME == "Idaho" | NAME == "Indiana")

# plot unemployment over time
unemployment_plot <-  plot_ly(filtered_data, x = ~Year, y = ~unemp_rate, 
                              color = ~NAME) %>% 
                              add_lines()

unemployment_plot<- unemployment_plot %>% layout(title = 'Unemployment Rate over Time',
  xaxis = list(title = 'Year'),
  yaxis = list (title = 'Unemployment Rate'))

unemployment_plot

# plot crime over time
crime_plot <-  plot_ly(filtered_data, x = ~Year, y = ~crime_rate, 
                              color = ~NAME) %>% 
                              add_lines()

crime_plot<- crime_plot %>% layout(title = 'Crime Rate over Time',
         xaxis = list(title = 'Year'),
         yaxis = list (title = 'Crime Rate'))


crime_plot

# Filter Data to 2014 
data_2014 = filter(data, Year == 2014)

#plot crime vs unemployment scatter plot
crime_vs_unemployment_plot <- plot_ly(data_2014, x = ~crime_rate, y = ~unemp_rate, color = ~NAME) %>% 
  add_markers()

crime_vs_unemployment_plot <- crime_vs_unemployment_plot %>% layout(title = 'Crime Rate over Time',
         xaxis = list(title = 'Year'),
         yaxis = list (title = 'Crime Rate'))

crime_vs_unemployment_plot


# plot spatial unemployment map
unemp_map = ggplot() +
  geom_sf(data=data_2014,aes(fill=(unemp_rate)))+
  scale_fill_viridis(option = "D")+
  annotation_scale(location = "bl")+   #0.002, upper,and 0.05 lower
  annotation_north_arrow(location = "br", which_north = "true", 
                         style = north_arrow_fancy_orienteering) +
  guides(fill=guide_legend(title="Unemployment Rate in 2014"))+
  xlab("Longitude") + ylab("Latitude") +
  ggtitle("Unemployment Rate Map Over Contiguous US") 

unemp_map

# plot spatial crime map
crime_map = ggplot() +
  geom_sf(data=data_2014,aes(fill=crime_rate))+
  scale_fill_viridis()+
  annotation_scale(location = "bl")+   #0.002, upper,and 0.05 lower
  annotation_north_arrow(location = "br", which_north = "true", 
                         style = north_arrow_fancy_orienteering) +
  guides(fill=guide_legend(title="Crime Rate in 2014"))+
  xlab("Longitude") + ylab("Latitude") +
  ggtitle("Crime Rate Map Over Contiguous US") 

crime_map

```
